services:
  backend:
    build:
      context: ./docker/back
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
    container_name: composeback
    hostname: backendservice

  frontend:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
      args:
        NODE_REG: ${NODE_REG}
    container_name: composefront
    ports:
      - ${APP_GATEWAY_IP}:4322:80
