services:
  backend:
    build:
      context: ./docker/back
    container_name: composeback
    ports:
      - 3002:3001

  filesprovider:
    image: filesprovider
    container_name: files_db
    ports:
      - 4366:80

  frontend:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
      args:
        VITE_BACKEND: "http://localhost:3002"
    container_name: composefront
    ports:
      - 4322:80
