services:
  backend:
    build:
      context: ./docker/back
      args:
        PIP_INDEX_URL: ${PIP_INDEX_URL}
    container_name: composeback
    ports:
      - 3002:5000

  frontend:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
      args:
        VITE_BACKEND: "http://localhost:3002"
        NODE_REG: ${NODE_REG}
    container_name: composefront
    ports:
      - 4322:80
