version: '3'
services:
  eChart:
    container_name: maxwell
    image: mcr.microsoft.com/devcontainers/typescript-node
    network_mode: bridge
    volumes:
      - ../:/workspace
      - node_modules:/workspace/node_modules
      - configs:/home/node/configs
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 127.0.0.1:5173:5173
    env_file: ~/.env

volumes:
  node_modules:
    external: true
  configs:
    external: true
